services:
  sensor_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sensor_db
    ports:
      - "127.0.0.1:5433:5432"
  app:
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - sensor_db
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://sensor_db:5432/sensor_db'
      JAVA_OPTS: '-Xmx512m'