create table Sensor
(
    id   int generated by default as identity primary key,
    name varchar(30) not null unique
);

create table Measurement
(
    id         int generated by default as identity primary key,
    value      double precision not null,
    is_rainy    boolean          not null,
    time_of_measurement timestamp,
    sensor     varchar(30) references Sensor (name) on delete cascade
);